spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF8&useSSL=false
    username: testuser
    password: TestTestTest123!
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-handlers-package: info.matsumana.typehandler
